# Project: ITProject
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ConsoleApp.o List.o
LINKOBJ  = ConsoleApp.o List.o
LIBS     = -L"D:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"D:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"D:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = ITProject.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Program Files\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

ConsoleApp.o: ConsoleApp.cpp
	$(CPP) -c ConsoleApp.cpp -o ConsoleApp.o $(CXXFLAGS)

List.o: List.cpp
	$(CPP) -c List.cpp -o List.o $(CXXFLAGS)
